# Generated by Django 4.1.1 on 2022-09-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_contact_body_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
